### ISSUE TITLE
Not working on OS X

### ISSUE THREAD

**Issue by thistehneisen** [RealOrangeOne/pranklock#1]
1) Installed "brew install xdotool" that was required, but missing on OS X
2) Did
- defaults write org.macosforge.xquartz.X11 enable_test_extensions -boolean true
- defaults write org.x.X11 enable_test_extensions -boolean true
3) Outputting: pranklock: line 12: 19563 Segmentation fault: 11  xdotool key "Super_L+l"

**Comment by RealOrangeOne** [comment]
macOS is unfortunately unsupported, due to a dependency on `i3lock`.

If there's an alternative application available, i'd definitely welcome a PR which adds support!

I suspect the reason this is erroring is because macOS doesn't have a `Super_L` key.
